# Generated by Django 4.1 on 2022-09-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('stud_name', models.CharField(max_length=55)),
                ('stud_addres', models.CharField(max_length=60)),
                ('stud_phone', models.IntegerField()),
            ],
        ),
    ]
