# Generated by Django 4.1 on 2022-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_rename_stud_addres_papa_stud_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papa',
            new_name='Student',
        ),
    ]
