# Generated by Django 4.1 on 2022-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_rename_stud_name_student_stud_brother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_brother',
            new_name='stud_name',
        ),
    ]
