# Generated by Django 4.1 on 2022-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_rename_stud_brother_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_phone',
            field=models.CharField(max_length=40),
        ),
    ]
