# Generated by Django 4.1 on 2022-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_rename_stud_id_student_stud_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_ids',
            new_name='stud_id',
        ),
    ]
