# Generated by Django 4.1 on 2022-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_alter_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_address',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(choices=[('111', 'Dhaval'), ('222', 'Jaydip'), ('333', 'Jaymeet'), ('444', 'Sagar'), ('555', 'Karan')], max_length=255),
        ),
    ]
