# Generated by Django 4.1 on 2022-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_alter_student_stud_address_alter_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_address',
            field=models.CharField(max_length=25),
        ),
    ]
