# Generated by Django 4.1 on 2022-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_alter_student_stud_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=255),
        ),
    ]
