# Generated by Django 4.1.1 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_alter_student_stud_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_role',
            field=models.CharField(choices=[('Python Dev', 1), ('React Dev', 2), ('Php Dev', 3)], default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
