# Generated by Django 4.1.1 on 2022-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_student_stud_role_alter_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_role',
            field=models.CharField(choices=[('Python Dev', 1), ('React Dev', 2), ('PhP Dev', 3)], default='None', max_length=40),
        ),
    ]
