# Generated by Django 4.1.1 on 2022-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_alter_student_stud_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(verbose_name='STUD_ID'),
        ),
    ]
