# Generated by Django 4.1.1 on 2022-10-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_alter_student_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_address',
            field=models.CharField(max_length=25, verbose_name='Hometown'),
        ),
    ]
